spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thetiptop
    username: tiptop
    password: tiptop
  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 200
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: thetiptop
  flyway:
    enabled: true
    default-schema: thetiptop
    schemas: thetiptop
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

tiptop:
  security:
    jwt:
      secret: "S3cr3tKey-Change-Me-Please-1234567890"
      expiration: 3600 # seconds
